[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript"
