#!/bin/bash

# This script passes system environment variables to Vite
source ~/.zshrc

# Pass the environment variables to the Vite dev server
VITE_SUPABASE_URL=$SUPABASEURLST \
VITE_SUPABASE_SERVICE_KEY=$SUPABASESERVICEKEYST \
VITE_SUPABASE_API_KEY=$SUPABASEAPIKEYST \
VITE_BASE_API_URL=$BASE_API_URL \
VITE_DEV_BASE_API_URL=$DEV_BASE_API_URL \
VITE_DEV_USERNAME=$DEV_USERNAME \
VITE_DEV_PASSWORD=$DEV_PASSWORD \
npm run dev