version: "3.9"

services:
  backend:
    env_file:
      - .env.development
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    env_file:
      - .env.development
    ports:
      - "8080:8080"
    command: ["npm", "run", "dev"]

