version: "3.9"

services:
  backend:
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    command: ["npm", "run", "build"]
    volumes:
      - ./sdr_frontend/dist:/app/dist

  db:
    image: postgres:15
    container_name: sdr_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

