version: "3.9"

services:
  backend:
    build: ./sdr_backend
    container_name: sdr_backend
    volumes:
      - ./sdr_backend:/app
    depends_on:
      - db

  frontend:
    build: ./sdr_frontend
    container_name: sdr_frontend
    volumes:
      - ./sdr_frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: sdr_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
