steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/securetrack-repo/securetrack-service', '.']
    dir: 'sdr_backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/securetrack-repo/securetrack-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'securetrack-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/securetrack-repo/securetrack-service'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1' # region
      - '--allow-unauthenticated'
      - '--service-account=cloudbuild@securetrack-457423.iam.gserviceaccount.com'
      - 'SUPABASE_PROJECT_URL=https://yinltryamlaidmexpvnx.supabase.co,SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpbmx0cnlhbWxhaWRtZXhwdm54Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTM5ODE2OCwiZXhwIjoyMDU2OTc0MTY4fQ.fij-xrU-WolOzB3L-QhJZP_x11XmBhipfc2enONyuYI'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/securetrack-repo/securetrack-service'

options:
  logging: CLOUD_LOGGING_ONLY

