steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/securetrack-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/securetrack-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'securetrack-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/securetrack-service'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1' # region
      - '--allow-unauthenticated'
      - '--service-account=416249990421@cloudbuild.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/securetrack-service'

options:
  logging: CLOUD_LOGGING_ONLY

