# Makefile
tools-install:
	@curl -fsSL https://d2lang.com/install.sh | sh

# Windows :
# powershell irm https://d2lang.com/install.ps1 | iex; Move-Item d2.exe C:\tools\d2\d2.exe -Force; setx Path "$($Env:Path);C:\tools\d2"
