training_data = [
        # Diagram modification examples
        {"text": "Add a database node", "label": 0},
        {"text": "Ad a node", "label": 0},
        {"text": "Creat a server", "label": 0},
        {"text": "Create a load balancer", "label": 0},
        {"text": "Remove the API gateway", "label": 0},
        {"text": "Connect the web server to the database", "label": 0},
        {"text": "Add three microservices", "label": 0},
        {"text": "Delete the connection between auth and API", "label": 0},
        {"text": "Move the database node to the right", "label": 0},
        {"text": "Rename the auth service to authentication service", "label": 0},
        {"text": "Add a firewall to protect the web tier", "label": 0},
        {"text": "Create a three-tier architecture", "label": 0},
        {"text": "Insert a caching layer", "label": 0},
        {"text": "Put a load balancer in front of the web servers", "label": 0},
        {"text": "Add message queue between services", "label": 0},
        {"text": "Make the database redundant", "label": 0},
        {"text": "Implement a VPN connection", "label": 0},
        
        # Diagram query examples
        {"text": "How is the authentication node connected?", "label": 1},
        {"text": "Wuts security like?", "label": 1},
        {"text": "How do I make this good?", "label": 1},
        {"text": "What components are in my architecture?", "label": 1},
        {"text": "Show me all connections to the database", "label": 1},
        {"text": "Is this architecture secure?", "label": 1},
        {"text": "How many microservices do I have?", "label": 1},
        {"text": "What's connected to the load balancer?", "label": 1},
        {"text": "Explain how data flows in this diagram", "label": 1},
        {"text": "What security measures are in this diagram?", "label": 1},
        {"text": "Are there any single points of failure?", "label": 1},
        {"text": "Which components can access the database directly?", "label": 1},
        {"text": "How many nodes are in the diagram?", "label": 1},
        {"text": "What type of database am I using?", "label": 1},
        {"text": "What's the purpose of this architecture?", "label": 1},
        {"text": "Can you analyze this diagram for security issues?", "label": 1},
        {"text": "Describe the components in this architecture", "label": 1},
        {"text": "Help me fix this", "label": 1},
        {"text": "Make it work better", "label": 1},
        {"text": "Make it work faster", "label": 1},
        {"text": "Make it work more efficiently", "label": 1},
        {"text": "Make it work more securely", "label": 1},
        {"text": "Make it work more reliably", "label": 1},
        {"text": "Make it work more scalably", "label": 1},
        
        
        # Expert advice examples
        {"text": "What's the best security practice for APIs?", "label": 2},
        {"text": "How should I secure my microservices?", "label": 2},
        {"text": "Explain Zero Trust Architecture", "label": 2},
        {"text": "What are best practices for database security?", "label": 2},
        {"text": "Should I use OAuth or JWT?", "label": 2},
        {"text": "Explain the difference between REST and GraphQL", "label": 2},
        {"text": "What's the CAP theorem?", "label": 2},
        {"text": "How do I implement HTTPS properly?", "label": 2},
        {"text": "What's the most secure way to store passwords?", "label": 2},
        {"text": "What are the OWASP top 10?", "label": 2},
        {"text": "How do I protect against SQL injection?", "label": 2},
        {"text": "What's the difference between synchronous and asynchronous communication?", "label": 2},
        {"text": "Explain event-driven architecture", "label": 2},
        {"text": "What is CQRS pattern?", "label": 2},
        {"text": "What are security considerations for cloud deployments?", "label": 2}
    ]