"""user_tenant_association table id column removed

Revision ID: 0f61298aa77e
Revises: af72ac31043d
Create Date: 2025-03-10 21:42:28.010645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f61298aa77e'
down_revision: Union[str, None] = 'af72ac31043d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tenant_association_id', table_name='user_tenant_association')
    op.drop_column('user_tenant_association', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tenant_association', sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.create_index('ix_user_tenant_association_id', 'user_tenant_association', ['id'], unique=False)
    # ### end Alembic commands ###
