"""added diagram_hash to reports table

Revision ID: 327d6229e2cf
Revises: 99e90f56975c
Create Date: 2025-06-22 22:31:14.127390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '327d6229e2cf'
down_revision: Union[str, None] = '99e90f56975c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('diagram_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'template_visibility',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('templates', 'template_tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('templates', 'template_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'tenant_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'template_id',
               existing_type=sa.String(length=4),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('reports', 'diagram_hash')
    # ### end Alembic commands ###
