"""added version field to sessions table

Revision ID: 3631cac7e44e
Revises: f5a424702973
Create Date: 2025-04-28 18:03:43.561202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3631cac7e44e'
down_revision: Union[str, None] = 'f5a424702973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'version')
    # ### end Alembic commands ###
