"""create templates table with diagram state column update

Revision ID: 46c171ad73eb
Revises: c0e140c9e878
Create Date: 2025-06-11 17:19:17.229079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46c171ad73eb'
down_revision: Union[str, None] = 'c0e140c9e878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('diagram_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('templates', 'diagram_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('diagram_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('templates', 'diagram_state')
    # ### end Alembic commands ###
