"""added assigned_to column to projects

Revision ID: 72e92e093b24
Revises: 52dce25915cf
Create Date: 2025-03-09 16:49:26.143775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e92e093b24'
down_revision: Union[str, None] = '52dce25915cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assigned_to', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'assigned_to')
    # ### end Alembic commands ###
