"""removed dfd_generation stus and changed dfd_data data type

Revision ID: 7b3df9e38b93
Revises: 7589159a3f68
Create Date: 2025-04-12 20:02:07.515671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3df9e38b93'
down_revision: Union[str, None] = '7589159a3f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_dfd_generation_status', table_name='projects')
    op.drop_column('projects', 'dfd_generation_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dfd_generation_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_projects_dfd_generation_status', 'projects', ['dfd_generation_status'], unique=False)
    # ### end Alembic commands ###
