"""dfd fields update

Revision ID: b534d8caed62
Revises: 0f61298aa77e
Create Date: 2025-03-29 23:08:36.020934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b534d8caed62'
down_revision: Union[str, None] = '0f61298aa77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('threat_model_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('dfd_generation_status', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('dfd_model', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('diagram_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_projects_dfd_generation_status'), 'projects', ['dfd_generation_status'], unique=False)
    op.create_index(op.f('ix_projects_threat_model_id'), 'projects', ['threat_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_threat_model_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_dfd_generation_status'), table_name='projects')
    op.drop_column('projects', 'diagram_updated_at')
    op.drop_column('projects', 'dfd_model')
    op.drop_column('projects', 'dfd_generation_status')
    op.drop_column('projects', 'threat_model_id')
    # ### end Alembic commands ###
