"""rename dfd_model to dfd_data

Revision ID: bbf28b63a6cc
Revises: b534d8caed62
Create Date: 2025-03-30 18:08:49.889629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbf28b63a6cc'
down_revision: Union[str, None] = 'b534d8caed62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dfd_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('projects', 'dfd_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dfd_model', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('projects', 'dfd_data')
    # ### end Alembic commands ###
