"""create templates table

Revision ID: c0e140c9e878
Revises: 3631cac7e44e
Create Date: 2025-06-11 17:00:27.681688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0e140c9e878'
down_revision: Union[str, None] = '3631cac7e44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=4), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('diagram_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_description', sa.Text(), nullable=True),
    sa.Column('template_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('template_visibility', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_template_id'), 'templates', ['template_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_template_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
