"""revamp to user tenant association table

Revision ID: d755eeaa8f7e
Revises: 
Create Date: 2025-03-08 01:02:01.924630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd755eeaa8f7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('user_tenant_association', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_tenant_association', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_tenant_association', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_user_tenant_association_id'), 'user_tenant_association', ['id'], unique=False)
    op.drop_constraint('user_tenant_association_user_id_fkey', 'user_tenant_association', type_='foreignkey')
    op.drop_constraint('user_tenant_association_tenant_id_fkey', 'user_tenant_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_tenant_association', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tenant_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'user_tenant_association', type_='foreignkey')
    op.drop_constraint(None, 'user_tenant_association', type_='foreignkey')
    op.create_foreign_key('user_tenant_association_tenant_id_fkey', 'user_tenant_association', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('user_tenant_association_user_id_fkey', 'user_tenant_association', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_tenant_association_id'), table_name='user_tenant_association')
    op.drop_column('user_tenant_association', 'updated_at')
    op.drop_column('user_tenant_association', 'created_at')
    op.drop_column('user_tenant_association', 'id')
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
